version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/usr/src/app
    environment:
      - NG_CLI_ANALYTICS=false

